# Generated by Django 4.0.4 on 2022-07-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TbPodr',
        ),
        migrations.AlterField(
            model_name='divisiontwo',
            name='position',
            field=models.CharField(default='Engineer', max_length=256, verbose_name='Должность'),
        ),
    ]
