# Generated by Django 4.0.6 on 2022-07-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0002_delete_tbpodr_alter_divisiontwo_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='ppe.divisionthree', verbose_name='СП 3-го уровня'),
        ),
    ]
